-- SQLite

-- MAKING TABLES
-- CREATE TABLE IDEOLOGY
-- (
--   ID     FLOAT NULL    ,
--   RESULT TEXT  NULL    
-- );

-- CREATE TABLE MEMBERS
-- (
--   ID       FLOAT NULL    ,
--   NAME     TEXT  NULL    ,
--   AGE      FLOAT NULL    ,
--   SEX      TEXT  NULL    ,
--   POSITION TEXT  NULL    
-- );

-- INSERT INFOS
INSERT INTO IDEOLOGY (ID, RESULT) VALUES (10, '불순분자');
INSERT INTO IDEOLOGY (ID, RESULT) VALUES (20, '정상');
INSERT INTO IDEOLOGY (ID, RESULT) VALUES (30, '자유민주주의');
INSERT INTO IDEOLOGY (ID, RESULT) VALUES (40, '정상');
INSERT INTO IDEOLOGY (ID, RESULT) VALUES (50, '정직');
INSERT INTO IDEOLOGY (ID, RESULT) VALUES (60, '정상');
INSERT INTO MEMBERS (ID, NAME, AGE, SEX, POSITION) VALUES (10, '고상훈', 18, '남성', '행동대원');
INSERT INTO MEMBERS (ID, NAME, AGE, SEX, POSITION) VALUES (20, '아사코', 15, '여성', '행동대장');
INSERT INTO MEMBERS (ID, NAME, AGE, SEX, POSITION) VALUES (30, '김열정', 17, '남성', '저격수');
INSERT INTO MEMBERS (ID, NAME, AGE, SEX, POSITION) VALUES (40, '이윤화', 16, '여성', '적군 전략분석');
INSERT INTO MEMBERS (ID, NAME, AGE, SEX, POSITION) VALUES (50, '이루다', 16, '여성', '자금조달');
INSERT INTO MEMBERS (ID, NAME, AGE, SEX, POSITION) VALUES (60, '이기철', 18, '남성', '식량공급');
